config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  

  root 'feeds#index'

  resources :users do
    get :find_friends , on: :collection
    get :about_me , on: :collection
    get :email_search , on: :collection
    get :all_friends, on: :collection
  end

  resources :feeds, except: :new
  resources :friendships
  resources :bookmarks
  resources :friend_requests

  get 'friends/index'
  get 'friends/destroy'
  get 'friends/index'

  get 'facebooks/facebook_profile'

end

app/models/feed.rb
class Feed < ActiveRecord::Base

	#validates_presence_of :post
  	#validates_presence_of :image
    has_many :bookmarks, dependent: :destroy
  	validate :at_least_one
	
	belongs_to :user
	mount_uploader :image, ImageUploader

	enum status: [:for_all, :only_me, :friends]  

	scope :newest_first, -> {order(created_at: :desc)}

	
	scope :public_and_my_feeds , -> (user_id){where("status = ? or (status = ? and user_id = ?) ", Feed.statuses['for_all'], Feed.statuses['only_me'], user_id)}
 

#This code is written for validation between post and image, now user can post status or image or both, but cant set blank status

	def at_least_one
	  if [self.post, self.image].reject(&:blank?).size == 0
	    errors[:base] << ("Please choose at least one image or status")
	  end
	end      
	

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed , only: [:edit,:update,:show,:destroy]

  def index
    @users = User.all
    @feed = Feed.new
    @friend_request = FriendRequest.new
    @feeds =  if  current_user.present?
      Feed.public_and_my_feeds(current_user.id).newest_first
    else
      Feed.for_all.newest_first
    end
    # @feeds = current_user.feeds
    # @posts = Feed.ids(params[:id]).order("created_at DESC")
  end

  # def new
  #   @users = User.all
  #   @feed = Feed.new

  #   @feeds =  if  current_user.present?
  #     Feed.public_and_my_feeds(current_user.id).newest_first
  #   else
  #     Feed.for_all.newest_first
  #   end
  # end

  def create
    @feed = current_user.feeds.build(feed_params)
     @feeds =  if  current_user.present?
      Feed.public_and_my_feeds(current_user.id).newest_first
    else
      Feed.for_all.newest_first
    end
    if @feed.save
      flash[:success] = "Feed was succesfully created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @feed.update(feed_params)
      flash[:success] = "Feed Succesfully Updated"
      redirect_to feed_path(@feed)
    else
      render 'edit'
    end
  end

  def destroy
    if @feed.present?
      @feed.destroy 
    end
    redirect_to root_path
    end

  def show
    redirect_to root_path
  end

  def edit
     @friend_request = FriendRequest.new
    @users = User.all
    @feeds =  if  current_user.present?
      Feed.public_and_my_feeds(current_user.id).newest_first
    else
      Feed.public_feeds.newest_first
    end
  end

  private

  def set_feed
    @feed = current_user.feeds.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:post,:status,:image)
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%=render 'layouts/innerpage'%>

<div class="container page-content ">
  <div class="row">
    <!-- left links -->
    <div class="col-md-3">
      <div class="profile-nav">
        <div class="widget">
          <div class="widget-body">
            <div class="user-heading round">
              <a href="#">
                <img src=<%= asset_path 'guy-5.jpg' %> alt="">
              </a>
              <p>
                <%=current_user.full_name %>
              </p>
            </div>
            <ul class="nav nav-pills nav-stacked">
              <li class="active">
                 </i> <%= link_to "MY Profile Tab" , user_path(current_user) %>
              </li>       
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- end left links -->
    

    <!-- center posts -->
<div class="col-md-6">
  <div class="row">
    <!-- left posts-->
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-12">
          <!-- post state form -->
          <div class="row">
            <div class="ui-widget">
              <%= simple_form_for @friend_request do |f| %>
                <div class="row" >
                  <div class="col-md-10">
                    <%= email_field_tag 'email', nil, data: {autocomplete_source: email_search_users_path}, id: 'user_email', class: "form-control", placeholder: "Enter Email for search user", required: true %>   
                  </div>
                  <div class="col-md-2  ">
                    <%= f.submit "Submit", class: "btn btn-azure pull-right" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <br>
          <div class="row">
            <%= form_for(@feed, :html=> {class: "form-horizontal", role: "form"}) do |f|%>
              <div class="box profile-info n-border-top">
                <form>
                  <%=f.text_field :post, class: "form-control input-lg p-text-area", placeholder: "Whats in your mind today?", autofocus: true%>
                </form>                      
                <div class="box-footer box-form">
                  <%=f.submit class: "btn btn-azure pull-right"%>
                    <p >
                      <%= f.file_field :image %>
                    </p>
                    <ul class="feed-post-form-input">
                      <li>
                        <%=f.radio_button :status, 'only_me'%>
                        <%=f.label :status, 'Only me' %>
                        <%=f.radio_button :status, 'for_all' %>
                        <%=f.label :status, 'public' %>
                        <%=f.radio_button :status, 'friends' %>
                        <%=f.label :status, 'friends' %>
                      </li>
                    </ul>
                </div>
              <%end%>
            </div>
        </div>
        <% @feeds.each do |feed|%>
          <% user = feed.user %>
            <div class="box box-widget">
              <div class="box-header with-border">
                <div class="user-block">
                  <img class="img-circle" src=<%= asset_path 'guy-5.jpg' %>  alt="User Image">
                  <span class="username"><a href="#"> <%= feed.user.first_name if feed.user %></a></span>
                  <span class="description"> <%= feed.created_at %></span>
                </div>
                <div class="box-tools">
                  <button type="button" class="btn btn-box-tool" data-widget="collapse">
                  <% if current_user == user %>
                    <%=link_to edit_feed_path(feed) do %>
                      <i class="fa fa-minus" style="color: black;"></i></button>
                      <button type="button" class="btn btn-box-tool" data-widget="remove">
                      <%=link_to feed_path(feed), method: :delete , data: {confirm: "Are you sure"} do %>
                        <i class="fa fa-times" style="color: black; border-color: #ccc;" ></i></button>
                      <% end %>
                    <% end %>
                  </button>
                  <% end %>
            </div>
 
                      <div class="user-block">  
                        <span class="username"><%#= user.first_name %></span>      
                      </div>

                      <div class="box-body" style="display: block;">
                        <p>
                          <%= feed.post %>  
                        </p>
                        <%= image_tag(feed.image)%>
                          <!-- <button type="button" class="btn btn-default btn-xs"><i class="fa fa-share"></i> Share</button> -->
                         
                          <!-- <span class="pull-right text-muted">127 likes - 3 comments</span> -->
                          <%if current_user.bookmarks.pluck(:feed_id).include?(feed.id)%>
                            <%#= link_to'<i class="icon-ok icon-white"></i> Bookmark Saved'.html_safe%>
                            <%= link_to '<button type="button" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up"></i>Bookmark Saved</button>'.html_safe%>
                            <%#= button_to "Bookmark saved",{class: 'btn btn-default btn-xs'}%>
                          <%else%>
                            <%= link_to '<button type="button" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up"></i>Bookmark </button>'.html_safe, {:controller => "bookmarks", :action => "create", :feed_id => feed.id }, :method => :post%>
                          <%end%>
                      </div>
                    </div>
                  </div>
              <% end %>
<!-- end post state form -->


              </div>
            </div>
          </div>
      <!-- end left posts-->
        </div>
      </div>
      <!-- end  center posts -->

      <!-- right posts -->
      <!-- end right posts -->
    </div>
  </div>
<div>
  <%= link_to "facebook friends" , facebooks_facebook_profile_path, class: "btn btn-xs btn-success"%>
</div>
<script>
  $( function() {

    $( "#user_email" ).autocomplete({
    source: $("#user_email").data('autocomplete-source')
    });

  } );
</script>

app/views/feeds/edit.html.erb
<%= render 'form'%>

app/views/feeds/index.html.erb
<%= render 'form'%>

app/views/feeds/new.html.erb
<%= render 'form'%>

app/views/feeds/show.html.erb
<nav class="navbar navbar-white navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><b>DayDay</b></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="actives"><a href="profile.html">Profile</a></li>
        <li><a href="home.html">Home</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Pages <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="profile2.html">Profile 2</a></li>
            <li><a href="profile3.html">Profile 3</a></li>
            <li><a href="profile4.html">Profile 4</a></li>
            <li><a href="sidebar_profile.html">Sidebar profile</a></li>
            <li><a href="user_detail.html">User detail</a></li>
            <li><a href="edit_profile.html">Edit profile</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="friends.html">Friends</a></li>
            <li><a href="friends2.html">Friends 2</a></li>
            <li><a href="profile_wall.html">Profile wall</a></li>
            <li><a href="photos1.html">Photos 1</a></li>
            <li><a href="photos2.html">Photos 2</a></li>
            <li><a href="view_photo.html">View photo</a></li>
            <li><a href="messages1.html">Messages 1</a></li>
            <li><a href="messages2.html">Messages 2</a></li>
            <li><a href="group.html">Group</a></li>
            <li><a href="list_users.html">List users</a></li>
            <li><a href="file_manager.html">File manager</a></li>
            <li><a href="people_directory.html">People directory</a></li>
            <li><a href="list_posts.html">List posts</a></li>
            <li><a href="grid_posts.html">Grid posts</a></li>
            <li><a href="forms.html">Forms</a></li>
            <li><a href="buttons.html">Buttons</a></li>
            <li><a href="error404.html">Error 404</a></li>
            <li><a href="error500.html">Error 500</a></li>
            <li><a href="recover_password.html">Recover password</a></li>
            <li><a href="registration_mail.html">Registration mail</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container page-content ">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">

    
             <div class="col-inside-lg decor-default activities animated fadeInUp" id="activities">
   <div class="unit">
    <h4 class="center description"><strong style="color: black;">Your Feeds</strong></h4>
      <div class="field date" style="color: black;">
      
      <%= simple_format(@feed.post) %>
      </div>
      <div class="article-actions">
        <%= link_to "Edit this post", edit_feed_path(@feed), class: "btn btn-xs btn-primary"%>
        <%= link_to "Delete this post", feed_path(@feed), method: :delete , 
                                            data: {confirm: "Are you sure you want to delete this post?"}, class: "btn btn-xs btn-success"%>

      <%= link_to "Back to Feed Listing" , new_feed_path, class: "btn btn-xs btn-success"%>
    </div>
     </div>

     </div>
  </div>
  </div>
</div>