config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  

  root 'feeds#index'

  resources :users do
    get :find_friends , on: :collection
    get :about_me , on: :collection
    get :email_search , on: :collection
    get :all_friends, on: :collection
  end

  resources :feeds, except: :new
  resources :friendships
  resources :bookmarks
  resources :friend_requests

  get 'friends/index'
  get 'friends/destroy'
  get 'friends/index'

  get 'facebooks/facebook_profile'

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :skip_email_validations

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :feeds, dependent: :destroy
  has_many :bookmarks , dependent: :destroy

  devise :omniauthable, :omniauth_providers => [:facebook , :twitter , :google_oauth2]

  # validates :provider, allow_nil: false 

  validates :email, uniqueness: false, if: :skip_email_validations

  # validates :provider, acceptance: true, allow_nil: false, on: :create


  # validates_presence_of :password_confirmation, :if => :should_confirm?

  def remove_friend(friend)
    friends.destroy(friend)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_friend?(user)
    friends.pluck(:id).include?(user.id)
  end

  def has_incoming_request_from?(user)
    FriendRequest.where(friend: self, user_id: user.id).present?
  end

  def has_sent_friend_request?(user)
    self.pending_friends.where(id: user.id).present?
  end

  def friend_request_for(user)
    self.friend_requests.where(friend_id: user.id).last
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    # user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end

 #  def self.from_omniauth_twitter(auth)

 #    user = where(provider: auth['provider'], uid: auth['uid']).first
 #    if user.present?
 #      user
 #    else
 #      user = User.new
 #      user.name = auth['name']
 #      user.email = auth['email']
 #      user.save

 #    end
    
 #    user
 #  end

  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.with_search(term, user)
    self.order(:email).where("email like ?", "#{term}%").reject{|u| u.is_friend?(user) || u.has_incoming_request_from?(user) || u.has_sent_friend_request?(user) || u.id == user.id}
  end

####################Koala ####################
  def koala_facebook
    @graph = Koala::Facebook::API.new(token)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @friendship = Friendship.new
    @user = User.find(params[:id])
  end

  def find_friends
    @users = User.all.reject{|u| u.id == current_user.id}
  end

  def all_friends
    @users = User.all.reject{|u| u.id == current_user.id}
    @incoming = FriendRequest.where(friend: current_user)
  end

  def add_friend
    
  end
  
  def remove_friend
    
  end

  def email_search
    @users = User.with_search(params[:term], current_user)
    render json: @users.map(&:email)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_about_me.html.erb
  
                <!-- Timeline -->
<div role="tabpanel" class="tab-pane active" id="timeline">
  <div class="row">
    <div class="col-md-5">
      <div class="widget">
        <div class="widget-header">
          <h3 class="widget-caption">About</h3>
        </div>
        <div class="widget-body bordered-top bordered-sky">
          <ul class="list-unstyled profile-about margin-none">
            <li class="padding-v-5">
              <div class="row">
                <div class="col-sm-4"><span class="text-muted">Date of Birth</span></div>
                <div class="col-sm-8"><%= @user.dob %></div>
              </div>
            </li>                       
            <li class="padding-v-5">
              <div class="row">
                <div class="col-sm-4"><span class="text-muted">Email</span></div>
                <div class="col-sm-8"><%= current_user.email %></div>
              </div>
            </li>
          </ul>
        </div>
      </div>
     </div>

   </div><!--row div close -->





<!--last  main div close here -->
</div>

app/views/users/_find_friends.html.erb
<!-- friends -->
<div role="tabpanel" class="tab-pane active" id="messages">
  <div class="row">  
    <% @users.each do |user| %>
      <div class="col-md-3">
        <div class="contact-box center-version">
          <a href="#">
            <h3 class="m-b-xs"><strong><%= user.full_name %></strong></h3>
            <div class="font-bold">Graphics designer</div>
          </a>
          <div class="contact-box-footer">
            <div class="m-t-xs btn-group">
              <% if current_user.is_friend?(user) %>
                <%= link_to "Unfriend", friends_destroy_path(id: user.id)%>
              <% elsif current_user.has_incoming_request_from?(user)%>
                <%  friend_request = FriendRequest.where(friend: current_user, user_id: user.id).last %>
                <%= link_to "Accept", friend_request, method: :patch %>
              <% elsif current_user.has_sent_friend_request?(user)%>
                <% friend_request = current_user.friend_request_for(user) %>
                <%= link_to "Cancel", friend_request, method: :delete%>
              <% else %>
                <%= link_to "Add Friend", friend_requests_path(friend_id: user.id), method: :post %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- end friends -->

app/views/users/_show.html.erb
  
                <!-- Timeline -->
<div role="tabpanel" class="tab-pane active" id="timeline">
  <div class="row">
    <div class="col-md-5">
      <div class="widget">
        <div class="widget-header">
          <h3 class="widget-caption">About</h3>
        </div>
        <div class="widget-body bordered-top bordered-sky">
          <ul class="list-unstyled profile-about margin-none">
            <li class="padding-v-5">
              <div class="row">
                <div class="col-sm-4"><span class="text-muted">Date of Birth</span></div>
                <div class="col-sm-8"><%= current_user.dob %></div>
              </div>
            </li>                       
            <li class="padding-v-5">
              <div class="row">
                <div class="col-sm-4"><span class="text-muted">Email</span></div>
                <div class="col-sm-8"><%= current_user.email %></div>
              </div>
            </li>
          </ul>
        </div>
      </div>
     </div>

   </div><!--row div close -->





<!--last  main div close here -->
</div>

app/views/users/all_friends.html.erb
<!-- friends -->
<%= render 'layouts/innerpage'%>

  <div class="row" style="margin-top: 100px">  
    <% @users.each do |user| %>
      <div class="col-md-3">
        <div class="contact-box center-version">
          <a href="#">
            <h3 class="m-b-xs"><strong><%= user.full_name %></strong></h3>
            <div class="font-bold">Graphics designer</div>
          </a>
          <div class="contact-box-footer">
            <div class="m-t-xs btn-group">
              <% if current_user.is_friend?(user) %>
                <%= link_to "Unfriend", friends_destroy_path(id: user.id)%>
              <% elsif current_user.has_incoming_request_from?(user)%>
                <%  friend_request = FriendRequest.where(friend: current_user, user_id: user.id).last %>
                <%= link_to "Accept", friend_request, method: :patch %>
              <% elsif current_user.has_sent_friend_request?(user)%>
                <% friend_request = current_user.friend_request_for(user) %>
                <%= link_to "Cancel", friend_request, method: :delete%>
              <% else %>
                <%= link_to "Add Friend", friend_requests_path(friend_id: user.id), method: :post %>
              <% end %>
               <%@incoming.each do |friend_request|%>
               <%= link_to "Reject", friend_request, method: :delete %>
               <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- end friends -->

app/views/users/find_friends.js.erb
$('li[role="presentation"]').removeClass('active');
$('.find-friends').addClass('active');
$('.tab-content').html("<%= j render 'users/find_friends' %>");

app/views/users/index.html.erb
   
<!-- friends -->
<div role="tabpanel " class="tab-pane active" id="messages">
  <div class="row">
  
    <% @users.friendships.each do |user| %>
      <% user.friendships.each do|f|%>
        
      
    <%# for friendship in @users.friendships%>
      <div class="col-md-3">
        <div class="contact-box center-version">
          <a href="#">
            <!-- <img alt="image" class="img-circle" src="./img/guy-5.jpg"> -->
            <h3 class="m-b-xs"><strong><%= f.friend.first_name %> <%= f.friend.last_name%></strong></h3>

            <div class="font-bold">Graphics designer</div>
            <%end%>
          </a>
          <div class="contact-box-footer">
            <div class="m-t-xs btn-group">
              <%= link_to "Add Friends", friendships_path(friend_id: user.id), method: :post %>
              
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div><!-- end friends -->

app/views/users/show.html.erb
<!-- Fixed navbar -->
<%=render 'layouts/innerpage'%>
  
     <div class="container page-content">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="row">
            <div class="col-md-12">
              <div class="bg-picture" style="background-image:url(<%= asset_path 'cover.jpg' %>)">
                <span class="bg-picture-overlay"></span><!-- overlay -->
                <!-- meta -->
                <div class="box-layout meta bottom">
                  <div class="col-md-6 clearfix">
                    <span class="img-wrapper pull-left m-r-15">
                      <img src="./img/guy-5.jpg" alt="" style="width:64px" class="br-radius">
                    </span>
                    <div class="media-body">
                      <h3 class="text-white mb-2 m-t-10 ellipsis"><%= current_user.first_name %> <%= current_user.last_name %></h3>
                      <h5 class="text-white"><%= current_user.dob %></h5>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="pull-right">
                      <div class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle btn btn-azure" href="#" aria-expanded="false"> Following <span class="caret"></span></a>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li><a href="#">Poke</a></li>
                            <li><a href="#">Private message</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Unfollow</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div><!--/ meta -->
              </div>
            </div>
          </div>
          <div class="row">
            <!-- Nav tabs -->
            <ul class="nav nav-pills nav-pills-custom-minimal custom-minimal-bottom profile-tabs">
                <li role="presentation" class="about-me active">
                  <%= link_to "About",  user_path(current_user), remote: true %></li>
                </li>
                
                <li role="presentation" class="find-friends">
                 
                <%#= link_to "Find Friends",  find_friends_users_path, remote: true %></li>
                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Photos</a></li>
                <li><%= link_to "all users" , all_friends_users_path %></li>
            </ul>

              <div class="tab-content">
                <!-- Timeline -->
                <%= render 'users/show' %>
              </div>
          </div>
         <div>

          <p><%#= link_to "Find Friends", users_path %></p>
          </div>
      </div>
   </div>
</div>

app/views/users/show.js.erb
$('li[role="presentation"]').removeClass('active');
$('.about-me').addClass('active');
$('.tab-content').html("<%= j render 'users/show' %>");