config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  

  root 'feeds#index'

  resources :users do
    get :find_friends , on: :collection
    get :about_me , on: :collection
    get :email_search , on: :collection
    get :all_friends, on: :collection
  end

  resources :feeds, except: :new
  resources :friendships
  resources :bookmarks
  resources :friend_requests

  get 'friends/index'
  get 'friends/destroy'
  get 'friends/index'

  get 'facebooks/facebook_profile'

end

app/views/layouts/_bookmarks.html.erb
<nav class="navbar navbar-white navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><b>GemsFriend</b>  
      </a>
 <a class="navbar-brand" href=""><b></b>  
      </a>
       <a class="navbar-brand" href=""><b></b>  
      </a>


       <a class="navbar-brand" href="index.html"><b>Bookmarks</b>  
      </a>


    </div>
    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav navbar-right">
        
        <strong>
           <%# if user_signed_in? %>
           <!--  Logged in as <strong><%= current_user.email %></strong>. -->
            <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %><!--  | -->
            <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <%# else %>
               
            <%# end %>
        </strong>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
           <%= current_user.first_name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></a></li>
            
            <li><%= link_to "Bookmarks", bookmarks_path, :class => 'navbar-link'  %></li>
            <li><a><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></a></li>
            <% else %>
            <% end %>
            
          </ul>
        </li>
      </ul>
    </div>
  </div>

</nav>

app/views/layouts/_innerpage.html.erb
<nav class="navbar navbar-white navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><b>GemsFriend</b></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
           <%= current_user.first_name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></a></li>
           
            <li><%= link_to "Bookmarks", bookmarks_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Friend Requests", friend_requests_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Friends", friends_index_path, :class => 'navbar-link'  %></li>
             <li><a><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></a></li>
            <% else %>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>

</nav>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-fixed-top navbar-transparent" role="navigation">
        <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button id="menu-toggle" type="button" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar bar1"></span>
            <span class="icon-bar bar2"></span>
            <span class="icon-bar bar3"></span>
          </button>
          <a class="navbar-brand" href="profile.html">GemsFriend  </a>
        </div>
          
      </div>
    </nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>
<body>
  <% if notice %>
     <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

<div>
<%= yield %>
</div>
 <div style="color: black;
  <% if user_signed_in? %>
    /*Logged in as <strong><%#= current_user.email %></strong>*/
    <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <%#= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    
  <%else %>
       
  <% end %>
</p>
</div> 
</body>
</html>